name: weatherapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  http: ^0.13.6
  intl: ^0.18.1
  lottie: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - animation/loading.json
    - animation/night.json
    - animation/day.json
    - images/day.jpg
    - WMO/0.png
    - WMO/1_3.png
    - WMO/2_45_48.png
    - WMO/51_53.png
    - WMO/55_56_57.png
    - WMO/61_63_66_80_81.png
    - WMO/65_67_82.png
    - WMO/71_73_75_77_85_86.png
    - WMO/80_81_82.png
    - WMO/95.png
    - WMO/96_99.png



  uses-material-design: true
